// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uoyvzyjtijtnfazythca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVveXZ6eWp0aWp0bmZhenl0aGNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3NjY4OTYsImV4cCI6MjA1NjM0Mjg5Nn0.iAt_J6sMUdPKR4kUPuZ4aD9VulzcTmz2BiQB1Lw-WuU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);